name: calculator
description: calculator
version: 1.0.0
repository: https://github.com/CHOISHO/calculator

environment:
  sdk: ^3.4.3

dependencies:
  args: ^2.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.0.17
  build_runner: ^2.3.3

